// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/actions/history': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/actions/history.get').default>>>>
    }
    '/api/actions/likes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/actions/likes.get').default>>>>
    }
    '/api/actions/reactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/actions/reactions.get').default>>>>
    }
    '/api/actions/reposts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/actions/reposts.get').default>>>>
    }
    '/api/admin/users/:id/badges': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/badges.put').default>>>>
    }
    '/api/auth/github/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/github/callback.get').default>>>>
    }
    '/api/auth/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/github/index.get').default>>>>
    }
    '/api/auth/google/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google/callback.get').default>>>>
    }
    '/api/auth/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google/index.get').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/signin': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signin.post').default>>>>
    }
    '/api/auth/signout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signout.post').default>>>>
    }
    '/api/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signup.post').default>>>>
    }
    '/api/bookmarks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookmarks.get').default>>>>
    }
    '/api/bookmarks/toggle': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookmarks/toggle.post').default>>>>
    }
    '/api/bridge/call': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bridge/call.post').default>>>>
    }
    '/api/bridge/plugins': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bridge/plugins.get').default>>>>
    }
    '/api/bridge/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bridge/register.post').default>>>>
    }
    '/api/bridge/relay': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bridge/relay.post').default>>>>
    }
    '/api/bridge/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bridge/status.get').default>>>>
    }
    '/api/dm/channels/:id/messages/:msgId/edits': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dm/channels/[id]/messages/[msgId]/edits.get').default>>>>
    }
    '/api/dm/channels/:id/messages/:msgId': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dm/channels/[id]/messages/[msgId]/index.patch').default>>>>
    }
    '/api/dm/channels/:id/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dm/channels/[id]/messages/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dm/channels/[id]/messages/index.post').default>>>>
    }
    '/api/dm/channels/:id/voice/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dm/channels/[id]/voice/join.post').default>>>>
    }
    '/api/dm/channels/:id/voice/leave': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dm/channels/[id]/voice/leave.post').default>>>>
    }
    '/api/dm/channels/:id/voice/signal': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dm/channels/[id]/voice/signal.post').default>>>>
    }
    '/api/dm/channels': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dm/channels/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dm/channels/index.post').default>>>>
    }
    '/api/emojis/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/emojis/[id].delete').default>>>>
    }
    '/api/emojis': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/emojis/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/emojis/index.post').default>>>>
    }
    '/api/events': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/events.get').default>>>>
    }
    '/api/invites/:code': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invites/[code].get').default>>>>
    }
    '/api/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index.get').default>>>>
    }
    '/api/playlists/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/[id].put').default>>>>
    }
    '/api/playlists/:id/items': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/[id]/items.post').default>>>>
    }
    '/api/playlists/:id/items/:postId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/[id]/items/[postId].delete').default>>>>
    }
    '/api/playlists': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/playlists/index.post').default>>>>
    }
    '/api/posts/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id].get').default>>>>
    }
    '/api/posts/:id/comments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id]/comments/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id]/comments/index.post').default>>>>
    }
    '/api/posts/:id/reactions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id]/reactions.post').default>>>>
    }
    '/api/posts/:id/repost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id]/repost.post').default>>>>
    }
    '/api/posts/:id/unrepost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id]/unrepost.post').default>>>>
    }
    '/api/posts/:id/view': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id]/view.post').default>>>>
    }
    '/api/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.post').default>>>>
    }
    '/api/servers/:id/channels/:channelId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/channels/[channelId].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/channels/[channelId].put').default>>>>
    }
    '/api/servers/:id/channels/:channelId/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/channels/[channelId]/messages/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/channels/[channelId]/messages/index.post').default>>>>
    }
    '/api/servers/:id/channels/:channelId/voice/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/channels/[channelId]/voice/join.post').default>>>>
    }
    '/api/servers/:id/channels/:channelId/voice/leave': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/channels/[channelId]/voice/leave.post').default>>>>
    }
    '/api/servers/:id/channels/:channelId/voice/signal': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/channels/[channelId]/voice/signal.post').default>>>>
    }
    '/api/servers/:id/channels': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/channels/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/channels/index.post').default>>>>
    }
    '/api/servers/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/index.put').default>>>>
    }
    '/api/servers/:id/invites/:inviteId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/invites/[inviteId].delete').default>>>>
    }
    '/api/servers/:id/invites': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/invites/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/invites/index.post').default>>>>
    }
    '/api/servers/:id/members/:userId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/members/[userId].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/members/[userId].put').default>>>>
    }
    '/api/servers/:id/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/members/index.get').default>>>>
    }
    '/api/servers/:id/roles/:roleId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/roles/[roleId].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/roles/[roleId].put').default>>>>
    }
    '/api/servers/:id/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/roles/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/[id]/roles/index.post').default>>>>
    }
    '/api/servers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/index.post').default>>>>
    }
    '/api/servers/join/:code': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servers/join/[code].post').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/api/upload/avatar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/avatar.post').default>>>>
    }
    '/api/upload/banner': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/banner.post').default>>>>
    }
    '/api/upload/server/:id/banner': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/server/[id]/banner.post').default>>>>
    }
    '/api/upload/server/:id/icon': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/server/[id]/icon.post').default>>>>
    }
    '/api/users/:id/close-friends/delete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/close-friends/delete.delete').default>>>>
    }
    '/api/users/:id/close-friends': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/close-friends/index.get').default>>>>
    }
    '/api/users/:id/close-friends/post': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/close-friends/post.post').default>>>>
    }
    '/api/users/:id/follow': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/follow.post').default>>>>
    }
    '/api/users/:id/followers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/followers.get').default>>>>
    }
    '/api/users/:id/following': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/following.get').default>>>>
    }
    '/api/users/:id/friends/accept': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/friends/accept.post').default>>>>
    }
    '/api/users/:id/friends': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/friends/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/friends/index.post').default>>>>
    }
    '/api/users/:id/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/posts.get').default>>>>
    }
    '/api/users/:id/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/profile.get').default>>>>
    }
    '/api/users/:id/unfollow': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/unfollow.post').default>>>>
    }
    '/api/users/by-username/:username': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/by-username/[username].get').default>>>>
    }
    '/api/users/profile': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/profile.put').default>>>>
    }
    '/api/users/settings': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/settings.put').default>>>>
    }
    '/api/voice/turn': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/voice/turn.get').default>>>>
    }
    '/api/whiteboard/:roomKey': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whiteboard/[roomKey].get').default>>>>
    }
    '/api/whiteboard': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whiteboard/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}